NUMPY
 numpy is a fundamental library for scientific computing in Python.

It provides supports for arrays matrices along with a collection of mathematical functions to operate

on this data structures.
 basics of numpy focusing on arrays and vectorized operations.

In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
##crate 1d array
arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [ ]:
arr2=np.array([1,2,3,4])
arr2.reshape(1,4)#1 roe and 4 col


array([[1, 2, 3, 4]])

In [11]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
#2d array
arr2=np.array([[1,2,3,4,5],[7,8,9,10,11]])
print(arr2)
arr2.shape

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


(2, 5)

In [17]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#attributes of numpy
arr=np.array([[1,2,3],[4,5,6]])
print("array",arr)
print("hapes",arr.shape)
print("no of dimension",arr.ndim)
print("data types",arr.dtype)
print("item size",arr.itemsize)

array [[1 2 3]
 [4 5 6]]
hapes (2, 3)
no of dimension 2
data types int64
item size 8


In [32]:
#numpy vectorized operation
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])
#eelement wise add
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 7  9 11 13]
[-5 -5 -5 -5]
[ 6 14 24 36]
[0.16666667 0.28571429 0.375      0.44444444]


In [35]:
#universal fxns
arr=np.array([2,3,4,5])
#square root
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798]
[  7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.69314718 1.09861229 1.38629436 1.60943791]


In [37]:
#slicing operation and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
print(arr[0][1])

2


In [43]:
arr[2:]


array([[ 9, 10, 11, 12]])

In [42]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [44]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [46]:
print(arr[1:2,1:3])

[[6 7]]


In [47]:
#modify arra element
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [48]:
arr[2:]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [100 100 100 100]]


In [49]:
#statisticla concept=normalization
#to have a mean of 0 and SD deviation of 1
data=np.array([1,2,3,4])
#cal the mean and SD
mean=np.mean(data)
SD=np.std(data)
#normalizse the data
normal=(data-mean)/SD
print("normal data",normal)

normal data [-1.34164079 -0.4472136   0.4472136   1.34164079]


In [52]:
data =np.array([1,2,3,4,5])
#mean
mean=np.mean(arr)
print("meanf",mean)
median=np.median(data)
print("meadian",median)
sd=np.std(data)
print(sd)
va=np.var(data)
print(va)

meanf 44.583333333333336
meadian 3.0
1.4142135623730951
2.0


In [57]:
#logical operation
data=np.array([1,2,3,4,5,6,7,8,9])
data[(data>5)& (data<=6)]

array([6])